### ISSUE TITLE
Transition to Manifest v3

### ISSUE THREAD

**Issue by alisonjo315** [mdlutz24/drupal-meeting-parser#9]
When I did "load unpacked," it worked but threw an error:
> Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.

If I'm reading correctly, the extension will stop working in January 2023? -- or maybe it won't be able to be updated, and also can't be newly installed...?

**Comment by goba** [comment]
Good find! The content scripts attachment that we use seems to stay as-is at least based on https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/, so I proposed we try updating the version and see what happens. Needs manual testing, which I may be able to do later this week or after DrupalCon.
